### ISSUE TITLE
ReactQueryDevTools icon visible on every site

### ISSUE THREAD

**Issue by tstirrat** [sandervspl/auctionoton#1]
Hey, the icon is visible on every single website since a recent update:

<img width="373" alt="Screen Shot 2022-05-03 at 9 45 12 PM" src="https://user-images.githubusercontent.com/702990/166616920-f509ef43-2900-4ba6-9906-3df8e569af34.png">

**Comment by sandervspl** [comment]
Oh, that's bad. I'm on it. Thanks for reporting!

**Comment by sandervspl** [comment]
Should be fixed in the 3.1.1 release! Sadly, for Chrome this can take up to a day for them to process.

**Comment by tstirrat** [comment]
Thanks!
