### ISSUE TITLE
Feature Request: Lookup craft cost for craft spells

### ISSUE THREAD

**Issue by tstirrat** [sandervspl/auctionoton#2]
Is it possible to add a lookup for the craft cost on crafting spells?

e.g. https://tbc.wowhead.com/spell=31432/runic-spellthread could show craft cost (and even profit 🙏🏽 ) while https://tbc.wowhead.com/item=24274/runic-spellthread would show the market value?

**Comment by sandervspl** [comment]
Something like this is definitely on the roadmap! The foundation is ready, I just need to figure out the UX and honestly just more hours in a day.

**Comment by tstirrat** [comment]
Cool. Let me know if I can help or continue on with some existing work. I am a React + TS dev too.

I imagine the simplest UX could be exactly the same as your item page, but on the spell page

**Comment by sandervspl** [comment]
Any help is definitely appreciated!

**Comment by sandervspl** [comment]
@tstirrat Hi! I've finally had some time to work on this feature. You can see the progress in this pull request #3

**Comment by sandervspl** [comment]
Added in #7
